
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 7664
      MYSQL_DATABASE: sppedometer_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - speedometer-net

  backend:
    build: ./backend
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=7664
      - DB_NAME=sppedometer_db
      - NODE_ENV=production
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - speedometer-net

  frontend:
    build: ./speedometer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - speedometer-net

volumes:
  mysql_data:

networks:
  speedometer-net:

  